# Generated by Django 6.0.3 on 2026-03-26 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('voter_id_hash', models.CharField(max_length=64)),
                ('encrypted_choice', models.TextField()),
                ('receipt_hash', models.CharField(max_length=64, unique=True)),
                ('chain_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'votes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('voter_id_hash',), name='one_active_vote_per_voter')],
            },
        ),
    ]
