# Generated by Django 4.2.7 on 2026-03-29 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_vote_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='General Election', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('emoji', models.CharField(max_length=8)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='votes.election')),
            ],
            options={
                'db_table': 'election_candidates',
            },
        ),
        migrations.AddConstraint(
            model_name='electioncandidate',
            constraint=models.UniqueConstraint(fields=('election', 'name'), name='unique_candidate_name_per_election'),
        ),
    ]
