# Generated by Django 4.2.7 on 2026-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_vote_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voter_password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
