# Generated by Django 4.2.7 on 2026-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_election_voter_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='admin_password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='election',
            name='admin_token_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
